name: Project Stats
on: 
  workflow_dispatch:

  # force workflow to showup
  push:
    tags:
      - 'v0.0.0'

jobs:
  main:
    name: 'Run'
    uses: usf-cs272n-fall2024/cs272n-bot/.github/workflows/calc-stats.yml@main
    if: ${{ github.event_name != 'push' }}
    secrets: inherit
    permissions: write-all
